### PR TITLE
husain pic

### PR DESCRIPTION
**Pull request by husainkassamnath**
husain-kassamnath

### CODE REVIEW

**Comment by michaelsevilla** [comment]
@husainkassamnath: it looks like you are trying to commit from the `source` branch to the `master` branch -- as a result you see 10 commits/197 changed files in the pull request. Is this what you wanted?

**Comment by husainkassamnath** [comment]
No, I was trying to add my pic but mistakenly it landed here.

**Comment by michaelsevilla** [comment]
Ok. Can you fix this so we can merge the new picture? You should be able to push to this branch. :)

**Comment by csbao** [comment]
Husain, I went ahead and added your info and pic on there and pushed changes to source branch.

Can someone with access to the github account go to this repo's settings and in the GitHub pages section where it says "Your GitHub Pages site is currently being built from the master branch.", change "master branch" to "gh-pages" please? Thanks!

Also for future reference, see this:
https://github.com/systemslab/systemslab.github.io/wiki/Deployment

**Pull request closed without merging**
